version: '3.8'

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: your_app_frontend
    restart: always
    ports:
      - "8090:8090"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro

    depends_on:
      - backend
    networks:
      - app-network


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: your_app_backend
    restart: always
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_HOST: db
      DATABASE_USER: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_NAME: ${MYSQL_DATABASE}

    depends_on:
      - db
    networks:
      - app-network


  db:
    image: mysql:8.0
    container_name: mysqlDB
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadminMysql
    restart: always
    env_file:
      - ./.env
    ports:
      - "8010:8010"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: